services:
  linkshortener.api:
    image: linkshortener.api
    build:
      context: .
      dockerfile: LinkShortener.API/Dockerfile
      
  linkshortener.client:
    image: linkshortener.client
    build:
      context: .
      dockerfile: LinkShortener.Client/Dockerfile

